import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import {
  StyleProvider,
  legacyLogicalPropertiesTransformer,
  px2remTransformer
} from '@ant-design/cssinjs';
import './globals.css';
import StyledComponentsRegistry from '../../lib/AntdRegistry';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};
const px2rem = px2remTransformer({
  rootValue: 32 // 32px = 1rem; @default 16
});

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {/* <StyledComponentsRegistry>{children}</StyledComponentsRegistry> */}
        <StyleProvider
          hashPriority='high'
          transformers={[legacyLogicalPropertiesTransformer, px2rem]}
        >
          {children}
        </StyleProvider>
      </body>
    </html>
  );
}
