import type { Metadata } from 'next';
import { Content, Inter } from 'next/font/google';
import './globals.css';
import StyledComponentsRegistry from '../../lib/AntdRegistry';
import theme from '../../Theme/themeConfig';
import { ConfigProvider, theme as Theme } from 'antd';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <ConfigProvider theme={theme}>{children}</ConfigProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
